# Variable collection
one = input('What is your name? ').upper()
two = input('Name an animal: ').upper()
three = input('Name a place: ').upper()
four = input('Name a food: ').upper()
five = input('Name an adjective: ').upper()
six = input('Name an adjective: ').upper()
seven = input('Name an object: ').upper()
eight = input('Name an adjective: ').upper()
nine = input('Name an adjective: ').upper()
ten = input('Name an object: ').upper()
eleven = input('Name an adjective: ').upper()
twelve = input('Name an adjective: ').upper()

# STORY
print('\n')
print('-'*50)
print('"THE STORY OF {} & THE THREE {}S"'.format(one, two))
print('-'*50)
print('\n')

print('Once upon a time, {} went for a walk in the {}. Pretty soon, {} came upon a house. {} knocked, and when no one answered, {} walked right in.'.format(one, three, one, one, one))
print('\n')
print('At the table in the kitchen, there were three bowls of {}. {} was hungry, and tasted the {} from the first bowl.'.format(four, one, four))
print('\n')
print('"This {} is too {}!" {} exclaimed.'.format(four, five, one))
print('\n')
print('So, {} tasted the {} from the second bowl.'.format(one, four))
print('\n')
print('"This {} is too {}!" {} said.'.format(four, six, one))
print('\n')
print('So, {} tasted the last bowl of {}.'.format(one, four))
print('\n')
print('"Ahhhh, this {} is just right," {} said happily and ate it all up.'.format(four, one))
print('\n')
print("After {} had eaten the 3 {}'s breakfasts, {} was feeling a little tired. So {} walked into the living room and saw 3 {}s. {} sat in the first {} to rest {}'s feet.".format(one, two, one, one, seven, one, seven, one))
print('\n')
print('"This {} is too {}!" {} exclaimed.'.format(seven, eight, one))
print('\n')
print('So {} sat in the second {}.'.format(one, seven))
print('\n')
print('"This {} is too {}!" {} whined.'.format(seven, nine, one))
print('\n')
print('So {} tried the last and smallest {}.'.format(one, seven))
print('\n')
print('"Ahhhh, this {} is just right," {} sighed. But just as {} settled down into the {} to rest, it broke into pieces!'.format(seven, one, one, seven))
print('\n')
print('{} had just about enough by now, so {} went upstairs to the bedroom. {} lay down in the first {}, but it was too {}. Then {} lay down in the second {}, but it was too {}. Then {} lay down in the third {} and it was just right. {} fell asleep.'.format(one, one, one, ten, eleven, one, ten, twelve, one, ten, one))
print('\n')
print('As {} was sleeping, the 3 {}s came home.'.format(one, two))
print('\n')
print('"Someone\'s been eating my {}," growled the Papa {}.'.format(four, two))
print('\n')
print('"Someone\'s been eating my {}," said the Mama {}.'.format(four, two))
print('\n')
print('"Someone\'s been eating my {}, and they ate it all up!" cried the Baby {}.'.format(four, two))
print('\n')
print('"Someone\'s been sitting in my my {}," growled the Papa {}.'.format(seven, two))
print('\n')
print('"Someone\'s been sitting in my {}," said the Mama {}.'.format(seven, two))
print('\n')
print('"Someone\'s been sitting in my {}, and they broke it all to pieces!" cried the Baby {}.'.format(seven, two))
print('\n')
print('They decided to look around some more and when they got upstairs to the bedroom, Papa {} growled, "Someone\'s been sleeping in my {}!"'.format(two, ten))
print('\n')
print('"Someone\'s been sleeping in my {}, too!" said the Mama {}.'.format(ten, two))
print('\n')
print('"Someone\'s been sleeping in my {} and they\'re still there!" exclaimed Baby {}.'.format(ten, two))
print('\n')
print('Just then, {} woke up and saw the 3 {}s. {} screamed, "Help!" and jumped up and ran out of the room. {} ran down the stairs, opened the door, and ran away into the forest. And {} never returned to the home of the three {}s. But the 3 {}s never stopped hunting them, not until they day they all died.'.format(one, two, one, one, one, two, two))
print('\n')
print('THE END')
